version: '3.11.4'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  app:
    container_name: flask-container
    build: .
    entrypoint: python main.py
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
  redis:
    image: redis
    env_file: .env
    container_name: redis-container
    ports:
      - "6379:6379"
  nginx:
    image: nginx:1.21.6
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/